# Generated by Django 4.0.1 on 2022-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
